// GBEmmy
// Copyright (C) 2014 Tim Potze
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.
// 
// For more information, please refer to <http://unlicense.org>

namespace GBEmmy.Emulation.Processor
{
    public static class OpcodeTable
    {
        #region Cb

        public static readonly Opcode[] Cb =
        {
            new Opcode("RLC B", 2, 8),
            new Opcode("RLC C", 2, 8),
            new Opcode("RLC D", 2, 8),
            new Opcode("RLC E", 2, 8),
            new Opcode("RLC H", 2, 8),
            new Opcode("RLC L", 2, 8),
            new Opcode("RLC (HL)", 2, 16),
            new Opcode("RLC A", 2, 8),
            new Opcode("RRC B", 2, 8),
            new Opcode("RRC C", 2, 8),
            new Opcode("RRC D", 2, 8),
            new Opcode("RRC E", 2, 8),
            new Opcode("RRC H", 2, 8),
            new Opcode("RRC L", 2, 8),
            new Opcode("RRC (HL)", 2, 16),
            new Opcode("RRC A", 2, 8),
            new Opcode("RL B", 2, 8),
            new Opcode("RL C", 2, 8),
            new Opcode("RL D", 2, 8),
            new Opcode("RL E", 2, 8),
            new Opcode("RL H", 2, 8),
            new Opcode("RL L", 2, 8),
            new Opcode("RL (HL)", 2, 16),
            new Opcode("RL A", 2, 8),
            new Opcode("RR B", 2, 8),
            new Opcode("RR C", 2, 8),
            new Opcode("RR D", 2, 8),
            new Opcode("RR E", 2, 8),
            new Opcode("RR H", 2, 8),
            new Opcode("RR L", 2, 8),
            new Opcode("RR (HL)", 2, 16),
            new Opcode("RR A", 2, 8),
            new Opcode("SLA B", 2, 8),
            new Opcode("SLA C", 2, 8),
            new Opcode("SLA D", 2, 8),
            new Opcode("SLA E", 2, 8),
            new Opcode("SLA H", 2, 8),
            new Opcode("SLA L", 2, 8),
            new Opcode("SLA (HL)", 2, 16),
            new Opcode("SLA A", 2, 8),
            new Opcode("SRA B", 2, 8),
            new Opcode("SRA C", 2, 8),
            new Opcode("SRA D", 2, 8),
            new Opcode("SRA E", 2, 8),
            new Opcode("SRA H", 2, 8),
            new Opcode("SRA L", 2, 8),
            new Opcode("SRA (HL)", 2, 16),
            new Opcode("SRA A", 2, 8),
            new Opcode("SWAP B", 2, 8),
            new Opcode("SWAP C", 2, 8),
            new Opcode("SWAP D", 2, 8),
            new Opcode("SWAP E", 2, 8),
            new Opcode("SWAP H", 2, 8),
            new Opcode("SWAP L", 2, 8),
            new Opcode("SWAP (HL)", 2, 16),
            new Opcode("SWAP A", 2, 8),
            new Opcode("SRL B", 2, 8),
            new Opcode("SRL C", 2, 8),
            new Opcode("SRL D", 2, 8),
            new Opcode("SRL E", 2, 8),
            new Opcode("SRL H", 2, 8),
            new Opcode("SRL L", 2, 8),
            new Opcode("SRL (HL)", 2, 16),
            new Opcode("SRL A", 2, 8),
            new Opcode("BIT 0,B", 2, 8),
            new Opcode("BIT 0,C", 2, 8),
            new Opcode("BIT 0,D", 2, 8),
            new Opcode("BIT 0,E", 2, 8),
            new Opcode("BIT 0,H", 2, 8),
            new Opcode("BIT 0,L", 2, 8),
            new Opcode("BIT 0,(HL)", 2, 16),
            new Opcode("BIT 0,A", 2, 8),
            new Opcode("BIT 1,B", 2, 8),
            new Opcode("BIT 1,C", 2, 8),
            new Opcode("BIT 1,D", 2, 8),
            new Opcode("BIT 1,E", 2, 8),
            new Opcode("BIT 1,H", 2, 8),
            new Opcode("BIT 1,L", 2, 8),
            new Opcode("BIT 1,(HL)", 2, 16),
            new Opcode("BIT 1,A", 2, 8),
            new Opcode("BIT 2,B", 2, 8),
            new Opcode("BIT 2,C", 2, 8),
            new Opcode("BIT 2,D", 2, 8),
            new Opcode("BIT 2,E", 2, 8),
            new Opcode("BIT 2,H", 2, 8),
            new Opcode("BIT 2,L", 2, 8),
            new Opcode("BIT 2,(HL)", 2, 16),
            new Opcode("BIT 2,A", 2, 8),
            new Opcode("BIT 3,B", 2, 8),
            new Opcode("BIT 3,C", 2, 8),
            new Opcode("BIT 3,D", 2, 8),
            new Opcode("BIT 3,E", 2, 8),
            new Opcode("BIT 3,H", 2, 8),
            new Opcode("BIT 3,L", 2, 8),
            new Opcode("BIT 3,(HL)", 2, 16),
            new Opcode("BIT 3,A", 2, 8),
            new Opcode("BIT 4,B", 2, 8),
            new Opcode("BIT 4,C", 2, 8),
            new Opcode("BIT 4,D", 2, 8),
            new Opcode("BIT 4,E", 2, 8),
            new Opcode("BIT 4,H", 2, 8),
            new Opcode("BIT 4,L", 2, 8),
            new Opcode("BIT 4,(HL)", 2, 16),
            new Opcode("BIT 4,A", 2, 8),
            new Opcode("BIT 5,B", 2, 8),
            new Opcode("BIT 5,C", 2, 8),
            new Opcode("BIT 5,D", 2, 8),
            new Opcode("BIT 5,E", 2, 8),
            new Opcode("BIT 5,H", 2, 8),
            new Opcode("BIT 5,L", 2, 8),
            new Opcode("BIT 5,(HL)", 2, 16),
            new Opcode("BIT 5,A", 2, 8),
            new Opcode("BIT 6,B", 2, 8),
            new Opcode("BIT 6,C", 2, 8),
            new Opcode("BIT 6,D", 2, 8),
            new Opcode("BIT 6,E", 2, 8),
            new Opcode("BIT 6,H", 2, 8),
            new Opcode("BIT 6,L", 2, 8),
            new Opcode("BIT 6,(HL)", 2, 16),
            new Opcode("BIT 6,A", 2, 8),
            new Opcode("BIT 7,B", 2, 8),
            new Opcode("BIT 7,C", 2, 8),
            new Opcode("BIT 7,D", 2, 8),
            new Opcode("BIT 7,E", 2, 8),
            new Opcode("BIT 7,H", 2, 8),
            new Opcode("BIT 7,L", 2, 8),
            new Opcode("BIT 7,(HL)", 2, 16),
            new Opcode("BIT 7,A", 2, 8),
            new Opcode("RES 0,B", 2, 8),
            new Opcode("RES 0,C", 2, 8),
            new Opcode("RES 0,D", 2, 8),
            new Opcode("RES 0,E", 2, 8),
            new Opcode("RES 0,H", 2, 8),
            new Opcode("RES 0,L", 2, 8),
            new Opcode("RES 0,(HL)", 2, 16),
            new Opcode("RES 0,A", 2, 8),
            new Opcode("RES 1,B", 2, 8),
            new Opcode("RES 1,C", 2, 8),
            new Opcode("RES 1,D", 2, 8),
            new Opcode("RES 1,E", 2, 8),
            new Opcode("RES 1,H", 2, 8),
            new Opcode("RES 1,L", 2, 8),
            new Opcode("RES 1,(HL)", 2, 16),
            new Opcode("RES 1,A", 2, 8),
            new Opcode("RES 2,B", 2, 8),
            new Opcode("RES 2,C", 2, 8),
            new Opcode("RES 2,D", 2, 8),
            new Opcode("RES 2,E", 2, 8),
            new Opcode("RES 2,H", 2, 8),
            new Opcode("RES 2,L", 2, 8),
            new Opcode("RES 2,(HL)", 2, 16),
            new Opcode("RES 2,A", 2, 8),
            new Opcode("RES 3,B", 2, 8),
            new Opcode("RES 3,C", 2, 8),
            new Opcode("RES 3,D", 2, 8),
            new Opcode("RES 3,E", 2, 8),
            new Opcode("RES 3,H", 2, 8),
            new Opcode("RES 3,L", 2, 8),
            new Opcode("RES 3,(HL)", 2, 16),
            new Opcode("RES 3,A", 2, 8),
            new Opcode("RES 4,B", 2, 8),
            new Opcode("RES 4,C", 2, 8),
            new Opcode("RES 4,D", 2, 8),
            new Opcode("RES 4,E", 2, 8),
            new Opcode("RES 4,H", 2, 8),
            new Opcode("RES 4,L", 2, 8),
            new Opcode("RES 4,(HL)", 2, 16),
            new Opcode("RES 4,A", 2, 8),
            new Opcode("RES 5,B", 2, 8),
            new Opcode("RES 5,C", 2, 8),
            new Opcode("RES 5,D", 2, 8),
            new Opcode("RES 5,E", 2, 8),
            new Opcode("RES 5,H", 2, 8),
            new Opcode("RES 5,L", 2, 8),
            new Opcode("RES 5,(HL)", 2, 16),
            new Opcode("RES 5,A", 2, 8),
            new Opcode("RES 6,B", 2, 8),
            new Opcode("RES 6,C", 2, 8),
            new Opcode("RES 6,D", 2, 8),
            new Opcode("RES 6,E", 2, 8),
            new Opcode("RES 6,H", 2, 8),
            new Opcode("RES 6,L", 2, 8),
            new Opcode("RES 6,(HL)", 2, 16),
            new Opcode("RES 6,A", 2, 8),
            new Opcode("RES 7,B", 2, 8),
            new Opcode("RES 7,C", 2, 8),
            new Opcode("RES 7,D", 2, 8),
            new Opcode("RES 7,E", 2, 8),
            new Opcode("RES 7,H", 2, 8),
            new Opcode("RES 7,L", 2, 8),
            new Opcode("RES 7,(HL)", 2, 16),
            new Opcode("RES 7,A", 2, 8),
            new Opcode("SET 0,B", 2, 8),
            new Opcode("SET 0,C", 2, 8),
            new Opcode("SET 0,D", 2, 8),
            new Opcode("SET 0,E", 2, 8),
            new Opcode("SET 0,H", 2, 8),
            new Opcode("SET 0,L", 2, 8),
            new Opcode("SET 0,(HL)", 2, 16),
            new Opcode("SET 0,A", 2, 8),
            new Opcode("SET 1,B", 2, 8),
            new Opcode("SET 1,C", 2, 8),
            new Opcode("SET 1,D", 2, 8),
            new Opcode("SET 1,E", 2, 8),
            new Opcode("SET 1,H", 2, 8),
            new Opcode("SET 1,L", 2, 8),
            new Opcode("SET 1,(HL)", 2, 16),
            new Opcode("SET 1,A", 2, 8),
            new Opcode("SET 2,B", 2, 8),
            new Opcode("SET 2,C", 2, 8),
            new Opcode("SET 2,D", 2, 8),
            new Opcode("SET 2,E", 2, 8),
            new Opcode("SET 2,H", 2, 8),
            new Opcode("SET 2,L", 2, 8),
            new Opcode("SET 2,(HL)", 2, 16),
            new Opcode("SET 2,A", 2, 8),
            new Opcode("SET 3,B", 2, 8),
            new Opcode("SET 3,C", 2, 8),
            new Opcode("SET 3,D", 2, 8),
            new Opcode("SET 3,E", 2, 8),
            new Opcode("SET 3,H", 2, 8),
            new Opcode("SET 3,L", 2, 8),
            new Opcode("SET 3,(HL)", 2, 16),
            new Opcode("SET 3,A", 2, 8),
            new Opcode("SET 4,B", 2, 8),
            new Opcode("SET 4,C", 2, 8),
            new Opcode("SET 4,D", 2, 8),
            new Opcode("SET 4,E", 2, 8),
            new Opcode("SET 4,H", 2, 8),
            new Opcode("SET 4,L", 2, 8),
            new Opcode("SET 4,(HL)", 2, 16),
            new Opcode("SET 4,A", 2, 8),
            new Opcode("SET 5,B", 2, 8),
            new Opcode("SET 5,C", 2, 8),
            new Opcode("SET 5,D", 2, 8),
            new Opcode("SET 5,E", 2, 8),
            new Opcode("SET 5,H", 2, 8),
            new Opcode("SET 5,L", 2, 8),
            new Opcode("SET 5,(HL)", 2, 16),
            new Opcode("SET 5,A", 2, 8),
            new Opcode("SET 6,B", 2, 8),
            new Opcode("SET 6,C", 2, 8),
            new Opcode("SET 6,D", 2, 8),
            new Opcode("SET 6,E", 2, 8),
            new Opcode("SET 6,H", 2, 8),
            new Opcode("SET 6,L", 2, 8),
            new Opcode("SET 6,(HL)", 2, 16),
            new Opcode("SET 6,A", 2, 8),
            new Opcode("SET 7,B", 2, 8),
            new Opcode("SET 7,C", 2, 8),
            new Opcode("SET 7,D", 2, 8),
            new Opcode("SET 7,E", 2, 8),
            new Opcode("SET 7,H", 2, 8),
            new Opcode("SET 7,L", 2, 8),
            new Opcode("SET 7,(HL)", 2, 16),
            new Opcode("SET 7,A", 2, 8)
        };

        #endregion

        #region Base

        public static readonly Opcode[] Base =
        {
            new Opcode("NOP", 1, 4),
            new Opcode("LD BC,d16", 3, 12),
            new Opcode("LD (BC),A", 1, 8),
            new Opcode("INC BC", 1, 8),
            new Opcode("INC B", 1, 4),
            new Opcode("DEC B", 1, 4),
            new Opcode("LD B,d8", 2, 8),
            new Opcode("RLCA", 1, 4),
            new Opcode("LD (a16),SP", 3, 20),
            new Opcode("ADD HL,BC", 1, 8),
            new Opcode("LD A,(BC)", 1, 8),
            new Opcode("DEC BC", 1, 8),
            new Opcode("INC C", 1, 4),
            new Opcode("DEC C", 1, 4),
            new Opcode("LD C,d8", 2, 8),
            new Opcode("RRCA", 1, 4),
            new Opcode("STOP 0", 2, 4),
            new Opcode("LD DE,d16", 3, 12),
            new Opcode("LD (DE),A", 1, 8),
            new Opcode("INC DE", 1, 8),
            new Opcode("INC D", 1, 4),
            new Opcode("DEC D", 1, 4),
            new Opcode("LD D,d8", 2, 8),
            new Opcode("RLA", 1, 4),
            new Opcode("JR r8", 2, 12),
            new Opcode("ADD HL,DE", 1, 8),
            new Opcode("LD A,(DE)", 1, 8),
            new Opcode("DEC DE", 1, 8),
            new Opcode("INC E", 1, 4),
            new Opcode("DEC E", 1, 4),
            new Opcode("LD E,d8", 2, 8),
            new Opcode("RRA", 1, 4),
            new Opcode("JR NZ,r8", 2, 12, 8),
            new Opcode("LD HL,d16", 3, 12),
            new Opcode("LDI (HL),A", 1, 8),
            new Opcode("INC HL", 1, 8),
            new Opcode("INC H", 1, 4),
            new Opcode("DEC H", 1, 4),
            new Opcode("LD H,d8", 2, 8),
            new Opcode("DAA", 1, 4),
            new Opcode("JR Z,r8", 2, 12, 8),
            new Opcode("ADD HL,HL", 1, 8),
            new Opcode("LDI A,(HL)", 1, 8),
            new Opcode("DEC HL", 1, 8),
            new Opcode("INC L", 1, 4),
            new Opcode("DEC L", 1, 4),
            new Opcode("LD L,d8", 2, 8),
            new Opcode("CPL", 1, 4),
            new Opcode("JR NC,r8", 2, 12, 8),
            new Opcode("LD SP,d16", 3, 12),
            new Opcode("LDD (HL),A", 1, 8),
            new Opcode("INC SP", 1, 8),
            new Opcode("INC (HL)", 1, 12),
            new Opcode("DEC (HL)", 1, 12),
            new Opcode("LD (HL),d8", 2, 12),
            new Opcode("SCF", 1, 4),
            new Opcode("JR C,r8", 2, 12, 8),
            new Opcode("ADD HL,SP", 1, 8),
            new Opcode("LDD A,(HL)", 1, 8),
            new Opcode("DEC SP", 1, 8),
            new Opcode("INC A", 1, 4),
            new Opcode("DEC A", 1, 4),
            new Opcode("LD A,d8", 2, 8),
            new Opcode("CCF", 1, 4),
            new Opcode("LD B,B", 1, 4),
            new Opcode("LD B,C", 1, 4),
            new Opcode("LD B,D", 1, 4),
            new Opcode("LD B,E", 1, 4),
            new Opcode("LD B,H", 1, 4),
            new Opcode("LD B,L", 1, 4),
            new Opcode("LD B,(HL)", 1, 8),
            new Opcode("LD B,A", 1, 4),
            new Opcode("LD C,B", 1, 4),
            new Opcode("LD C,C", 1, 4),
            new Opcode("LD C,D", 1, 4),
            new Opcode("LD C,E", 1, 4),
            new Opcode("LD C,H", 1, 4),
            new Opcode("LD C,L", 1, 4),
            new Opcode("LD C,(HL)", 1, 8),
            new Opcode("LD C,A", 1, 4),
            new Opcode("LD D,B", 1, 4),
            new Opcode("LD D,C", 1, 4),
            new Opcode("LD D,D", 1, 4),
            new Opcode("LD D,E", 1, 4),
            new Opcode("LD D,H", 1, 4),
            new Opcode("LD D,L", 1, 4),
            new Opcode("LD D,(HL)", 1, 8),
            new Opcode("LD D,A", 1, 4),
            new Opcode("LD E,B", 1, 4),
            new Opcode("LD E,C", 1, 4),
            new Opcode("LD E,D", 1, 4),
            new Opcode("LD E,E", 1, 4),
            new Opcode("LD E,H", 1, 4),
            new Opcode("LD E,L", 1, 4),
            new Opcode("LD E,(HL)", 1, 8),
            new Opcode("LD E,A", 1, 4),
            new Opcode("LD H,B", 1, 4),
            new Opcode("LD H,C", 1, 4),
            new Opcode("LD H,D", 1, 4),
            new Opcode("LD H,E", 1, 4),
            new Opcode("LD H,H", 1, 4),
            new Opcode("LD H,L", 1, 4),
            new Opcode("LD H,(HL)", 1, 8),
            new Opcode("LD H,A", 1, 4),
            new Opcode("LD L,B", 1, 4),
            new Opcode("LD L,C", 1, 4),
            new Opcode("LD L,D", 1, 4),
            new Opcode("LD L,E", 1, 4),
            new Opcode("LD L,H", 1, 4),
            new Opcode("LD L,L", 1, 4),
            new Opcode("LD L,(HL)", 1, 8),
            new Opcode("LD L,A", 1, 4),
            new Opcode("LD (HL),B", 1, 8),
            new Opcode("LD (HL),C", 1, 8),
            new Opcode("LD (HL),D", 1, 8),
            new Opcode("LD (HL),E", 1, 8),
            new Opcode("LD (HL),H", 1, 8),
            new Opcode("LD (HL),L", 1, 8),
            new Opcode("HALT", 1, 4),
            new Opcode("LD (HL),A", 1, 8),
            new Opcode("LD A,B", 1, 4),
            new Opcode("LD A,C", 1, 4),
            new Opcode("LD A,D", 1, 4),
            new Opcode("LD A,E", 1, 4),
            new Opcode("LD A,H", 1, 4),
            new Opcode("LD A,L", 1, 4),
            new Opcode("LD A,(HL)", 1, 8),
            new Opcode("LD A,A", 1, 4),
            new Opcode("ADD A,B", 1, 4),
            new Opcode("ADD A,C", 1, 4),
            new Opcode("ADD A,D", 1, 4),
            new Opcode("ADD A,E", 1, 4),
            new Opcode("ADD A,H", 1, 4),
            new Opcode("ADD A,L", 1, 4),
            new Opcode("ADD A,(HL)", 1, 8),
            new Opcode("ADD A,A", 1, 4),
            new Opcode("ADC A,B", 1, 4),
            new Opcode("ADC A,C", 1, 4),
            new Opcode("ADC A,D", 1, 4),
            new Opcode("ADC A,E", 1, 4),
            new Opcode("ADC A,H", 1, 4),
            new Opcode("ADC A,L", 1, 4),
            new Opcode("ADC A,(HL)", 1, 8),
            new Opcode("ADC A,A", 1, 4),
            new Opcode("SUB B", 1, 4),
            new Opcode("SUB C", 1, 4),
            new Opcode("SUB D", 1, 4),
            new Opcode("SUB E", 1, 4),
            new Opcode("SUB H", 1, 4),
            new Opcode("SUB L", 1, 4),
            new Opcode("SUB (HL)", 1, 8),
            new Opcode("SUB A", 1, 4),
            new Opcode("SBC A,B", 1, 4),
            new Opcode("SBC A,C", 1, 4),
            new Opcode("SBC A,D", 1, 4),
            new Opcode("SBC A,E", 1, 4),
            new Opcode("SBC A,H", 1, 4),
            new Opcode("SBC A,L", 1, 4),
            new Opcode("SBC A,(HL)", 1, 8),
            new Opcode("SBC A,A", 1, 4),
            new Opcode("AND B", 1, 4),
            new Opcode("AND C", 1, 4),
            new Opcode("AND D", 1, 4),
            new Opcode("AND E", 1, 4),
            new Opcode("AND H", 1, 4),
            new Opcode("AND L", 1, 4),
            new Opcode("AND (HL)", 1, 8),
            new Opcode("AND A", 1, 4),
            new Opcode("XOR B", 1, 4),
            new Opcode("XOR C", 1, 4),
            new Opcode("XOR D", 1, 4),
            new Opcode("XOR E", 1, 4),
            new Opcode("XOR H", 1, 4),
            new Opcode("XOR L", 1, 4),
            new Opcode("XOR (HL)", 1, 8),
            new Opcode("XOR A", 1, 4),
            new Opcode("OR B", 1, 4),
            new Opcode("OR C", 1, 4),
            new Opcode("OR D", 1, 4),
            new Opcode("OR E", 1, 4),
            new Opcode("OR H", 1, 4),
            new Opcode("OR L", 1, 4),
            new Opcode("OR (HL)", 1, 8),
            new Opcode("OR A", 1, 4),
            new Opcode("CP B", 1, 4),
            new Opcode("CP C", 1, 4),
            new Opcode("CP D", 1, 4),
            new Opcode("CP E", 1, 4),
            new Opcode("CP H", 1, 4),
            new Opcode("CP L", 1, 4),
            new Opcode("CP (HL)", 1, 8),
            new Opcode("CP A", 1, 4),
            new Opcode("RET NZ", 1, 20, 8),
            new Opcode("POP BC", 1, 12),
            new Opcode("JP NZ,a16", 3, 16, 12),
            new Opcode("JP a16", 3, 16),
            new Opcode("CALL NZ,a16", 3, 24, 12),
            new Opcode("PUSH BC", 1, 16),
            new Opcode("ADD A,d8", 2, 8),
            new Opcode("RST 00H", 1, 16),
            new Opcode("RET Z", 1, 20, 8),
            new Opcode("RET", 1, 16),
            new Opcode("JP Z,a16", 3, 16, 12),
            new Opcode(), // new OpcodeInstruction("PREFIX CB", "- - - -", 1, 4),
            new Opcode("CALL Z,a16", 3, 24, 12),
            new Opcode("CALL a16", 3, 24),
            new Opcode("ADC A,d8", 2, 8),
            new Opcode("RST 08H", 1, 16),
            new Opcode("RET NC", 1, 20, 8),
            new Opcode("POP DE", 1, 12),
            new Opcode("JP NC,a16", 3, 16, 12),
            new Opcode("EMPTY", 0, 0),
            new Opcode("CALL NC,a16", 3, 24, 12),
            new Opcode("PUSH DE", 1, 16),
            new Opcode("SUB d8", 2, 8),
            new Opcode("RST 10H", 1, 16),
            new Opcode("RET C", 1, 20, 8),
            new Opcode("RETI", 1, 16),
            new Opcode("JP C,a16", 3, 16, 12),
            new Opcode("EMPTY", 0, 0),
            new Opcode("CALL C,a16", 3, 24, 12),
            new Opcode("EMPTY", 0, 0),
            new Opcode("SBC A,d8", 2, 8),
            new Opcode("RST 18H", 1, 16),
            new Opcode("LDH (a8),A", 2, 12),
            new Opcode("POP HL", 1, 12),
            new Opcode("LD (C),A", 2, 8),
            new Opcode("EMPTY", 0, 0),
            new Opcode("EMPTY", 0, 0),
            new Opcode("PUSH HL", 1, 16),
            new Opcode("AND d8", 2, 8),
            new Opcode("RST 20H", 1, 16),
            new Opcode("ADD SP,r8", 2, 16),
            new Opcode("JP (HL)", 1, 4),
            new Opcode("LD (a16),A", 3, 16),
            new Opcode("EMPTY", 0, 0),
            new Opcode("EMPTY", 0, 0),
            new Opcode("EMPTY", 0, 0),
            new Opcode("XOR d8", 2, 8),
            new Opcode("RST 28H", 1, 16),
            new Opcode("LDH A,(a8)", 2, 12),
            new Opcode("POP AF", 1, 12),
            new Opcode("LD A,(C)", 2, 8),
            new Opcode("DI", 1, 4),
            new Opcode("EMPTY", 0, 0),
            new Opcode("PUSH AF", 1, 16),
            new Opcode("OR d8", 2, 8),
            new Opcode("RST 30H", 1, 16),
            new Opcode("LDHL SP,r8", 2, 12),
            new Opcode("LD SP,HL", 1, 8),
            new Opcode("LD A,(a16)", 3, 16),
            new Opcode("EI", 1, 4),
            new Opcode("EMPTY", 0, 0),
            new Opcode("EMPTY", 0, 0),
            new Opcode("CP d8", 2, 8),
            new Opcode("RST 38H", 1, 16)
        };

        #endregion
    }
}